In [17]:
import cv2

In [18]:
img= cv2.imread ("shah.jpg",1)

In [19]:
print(img.shape)

(400, 700, 3)


In [4]:
print(img)

[[[239 233 234]
  [239 233 234]
  [239 233 234]
  ...
  [235 225 225]
  [235 225 225]
  [235 225 225]]

 [[237 231 232]
  [237 231 232]
  [237 231 232]
  ...
  [233 223 223]
  [233 223 223]
  [233 223 223]]

 [[235 229 230]
  [235 229 230]
  [234 228 229]
  ...
  [231 221 221]
  [231 221 221]
  [231 221 221]]

 ...

 [[235 225 225]
  [235 225 225]
  [234 224 224]
  ...
  [226 218 219]
  [227 219 220]
  [227 219 220]]

 [[237 227 227]
  [237 227 227]
  [237 227 227]
  ...
  [228 220 221]
  [229 221 222]
  [229 221 222]]

 [[239 229 229]
  [239 229 229]
  [239 229 229]
  ...
  [230 222 223]
  [231 223 224]
  [231 223 224]]]


In [5]:
print(type(img))

<class 'numpy.ndarray'>


In [6]:
resized = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("flower",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
face_cascade= cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [21]:
img

array([[[239, 233, 234],
        [239, 233, 234],
        [239, 233, 234],
        ...,
        [235, 225, 225],
        [235, 225, 225],
        [235, 225, 225]],

       [[237, 231, 232],
        [237, 231, 232],
        [237, 231, 232],
        ...,
        [233, 223, 223],
        [233, 223, 223],
        [233, 223, 223]],

       [[235, 229, 230],
        [235, 229, 230],
        [234, 228, 229],
        ...,
        [231, 221, 221],
        [231, 221, 221],
        [231, 221, 221]],

       ...,

       [[235, 225, 225],
        [235, 225, 225],
        [234, 224, 224],
        ...,
        [226, 218, 219],
        [227, 219, 220],
        [227, 219, 220]],

       [[237, 227, 227],
        [237, 227, 227],
        [237, 227, 227],
        ...,
        [228, 220, 221],
        [229, 221, 222],
        [229, 221, 222]],

       [[239, 229, 229],
        [239, 229, 229],
        [239, 229, 229],
        ...,
        [230, 222, 223],
        [231, 223, 224],
        [231, 223, 224]]

In [22]:
grey_img= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [23]:
grey_img

array([[234, 234, 234, ..., 226, 226, 226],
       [232, 232, 232, ..., 224, 224, 224],
       [230, 230, 229, ..., 222, 222, 222],
       ...,
       [226, 226, 225, ..., 219, 220, 220],
       [228, 228, 228, ..., 221, 222, 222],
       [230, 230, 230, ..., 223, 224, 224]], dtype=uint8)

In [24]:
faces=face_cascade.detectMultiScale(grey_img,scaleFactor=1.05,minNeighbors=5)

In [25]:
print(type(faces))

<class 'numpy.ndarray'>


In [26]:
print(faces)

[[343  33 100 100]
 [195  49  99  99]]


In [31]:
for x,y,w,h in faces:
    img=cv2.rectangle(img, (x,y), (x+w,y+h),(255,0,0),3)

In [32]:
cv2.imshow("grey",img)
cv2.waitKey(0)
cv2.destroyAllWindows()